### ISSUE TITLE
Update Newman orb examples and documentation on CircleCI

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/devrel-content#100]
### Describe the content you'd like to see

I believe their documentation is auto-generated from our repo, but if not, we can reach out to the CircleCI team to update the documentation on this page: https://circleci.com/developer/orbs/orb/postman/newman

The example should use the correct version of Newman. Can also include workflow yaml.

Example: https://youtu.be/mPZJdAH1alc

**Comment by seanryankeegan** [comment]
This has been updated and I believe this can be closed. @loopDelicious let me know if there's anything else you want to be done for this issue!
