### ISSUE TITLE
Automating Badge awarding on Badgr

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#108]
### Describe the content you'd like to see

For Galaxy Training we're still awarding badges manually. The idea is to have a collection that:
- validates the submission
- awards the badge on badgr

Anything else I'm missing?

### Content Type

Collection

**Comment by arlemi** [comment]
@Kcorb95 You may have already started looking into that, do you want to take it? Happy to collaborate on it too, should be a fun one!

**Comment by Kcorb95** [comment]
I'd love to help with this. I've been trying to think of ways to do this for a while and I agree, ideally we would just handle everything through Postman. 
Two of the issues that I was running into was getting users by their email and also awarding badges through the Discourse API did not seem to be [documented](https://docs.discourse.org/#tag/Badges) or possible to do. 
There are [some posts](https://meta.discourse.org/t/how-to-grant-a-custom-badge-through-the-api/103270) that I came across that made it seem like it was doable but I ran into issues with getting it to work. Let's figure this out!

**Comment by arlemi** [comment]
I just ticked that Discourse is only one part of the issue, the awarding on Badgr isn't automated either. 

@seanryankeegan Do you have any idea how we could automate the badgr part?

**Comment by arlemi** [comment]
Here's how @clairefro did it for the Student Expert badges: https://github.com/Postman-Student-Program/postman-submission-checker-api

**Comment by seanryankeegan** [comment]
@arlemi @Kcorb95 sorry I didn't respond sooner! But yeah, Claire was able to automate for the Student Program, so hopefully that link Arlemi passed along helps!

**Comment by clairefro** [comment]
Hi @arlemi and @seanryankeegan you found part of the process! The code above is just for remotely running Postman tests against a submitted collection. The actual Badgr automation takes place in a Google Apps script on the submissions spreadsheet. I will share an internal link to the docs

**Comment by arlemi** [comment]
Started a repo here to host the tests: https://github.com/postmanlabs/postman-badge-checker

@clairefro is updating the API so it can receive a file instead of a link

**Comment by arlemi** [comment]
Automated the badgr badging for APIs 101, API Tester and API adoption thanks to @clairefro 's badging API! 🙌 

We'll track other badges in #295 (as it'll be a different process), and discourse badges in #294.
