### ISSUE TITLE
GraphQL introspection level-up

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/devrel-content#110]
### Describe the content you'd like to see

video

### Content Type

Video - https://drive.google.com/drive/u/0/folders/10KLX7KOSw4n0NaXDO4aFJwXrQw-Dwpzj

Video metadata:

Title: GraphQL introspection
Description: GraphQL requests support introspection to fetch schemas automatically and enable you to auto-complete queries. To enable autocompletion, your request needs a GraphQL schema. Postman will automatically fetch a schema based on the request URL, using GraphQL introspection. 

Fork the example: https://www.postman.com/devrel/workspace/devrel-re-public/request/13191452-1dacadd2-2bfd-4408-877d-f764ff84fc3b
Docs: https://learning.postman.com/docs/sending-requests/supported-api-frameworks/graphql/#introspection-and-importing-graphql-schemas
Blog: https://blog.postman.com/introducing-automatic-schema-imports-for-graphql-requests/

### If the request is for a video, indicate which type

Level-Up

**Comment by loopDelicious** [comment]
@arlemi keywordlabeler is aggressive! I wrote the word `blog` to include a link to it in the video metadata, and now there's a `blog` label on this issue. No action needed, just general feedback for the bot.

**Comment by arlemi** [comment]
@loopDelicious It is, I made it so it would only add the tag when blog is written with a capital letter so it doesn't tag when it's the middle of a sentence, but I might need to find a better way. (more info on the filters here: https://github.com/postmanlabs/devrel-content/blob/main/.github/keylabeler.yml)

**Comment by loopDelicious** [comment]
ah - got it. i'll use lower case! this works!
