### ISSUE TITLE
Guide to APIs: REST, SOAP, GraphQL. When to use what?

### ISSUE THREAD

**Issue by ivikramsahu** [postmanlabs/devrel-content#112]
### Describe the content you'd like to see

Understanding and sharing different architectural overview that includes collection with some example and use cases.

### Content Type

Blog

**Comment by sahuvikramp** [comment]
Started working on blog post research part

**Comment by Kcorb95** [comment]
![image](https://user-images.githubusercontent.com/40337763/163474743-19d1a30d-eb16-48d2-ada0-35a877bb0136.png)
(please assign thanks 🙏)

**Comment by Kcorb95** [comment]
Begun search for candidates. Budget is < $1,500. Can try multiple authors at different tiers/prices to test quality.

**Comment by Kcorb95** [comment]
Five orders placed. Should have deliverables ready for review by end of next week.

**Comment by Kcorb95** [comment]
Technical review done, draft in for review with Linda.

**Comment by Kcorb95** [comment]
Done! 
https://blog.postman.com/guide-to-apis-rest-soap-graphql-grpc-websockets/
