### ISSUE TITLE
Update "First 5 Things to Try if You’re New to Postman" blog

### ISSUE THREAD

**Issue by claireriley** [postmanlabs/devrel-content#114]
### Describe the content you'd like to see

[This blog post](https://blog.postman.com/first-5-things-to-try-if-youre-new-to-postman/) is a great intro for beginners, but is now 4 years old and outdated. An updated version would be a great addition to the [docs intro page](https://learning.getpostman.com/docs/getting-started/introduction/) sidebar.

Sidenote: this blog post is the first item google returns when you search "new to postman"

### Content Type

Blog

**Comment by arlemi** [comment]
There you go @claireriley ! https://blog.postman.com/postman-first-5-things-to-try/
