### ISSUE TITLE
Create content on using a custom proxy

### ISSUE THREAD

**Issue by claireriley** [postmanlabs/devrel-content#116]
### Describe the content you'd like to see

It'd be great to have a new blog or video about configuring proxy settings and using a custom proxy for [this docs page](https://learning.postman.com/docs/getting-started/proxy/). There is [this video](https://youtu.be/bjrCHUITZ3k), but it doesn't cover the proxy config in Postman settings.

### Content Type

Video, Blog

**Comment by iandouglas** [comment]
Blog posts are taken care of by the marketing team already and @loopDelicious is working on updated videos.
