### ISSUE TITLE
Create video(s) on pre-request scripts

### ISSUE THREAD

**Issue by claireriley** [postmanlabs/devrel-content#118]
### Describe the content you'd like to see

There doesn't seem to be much recent video content on pre-request scripts. If a new video or multiple are created, it'd be a good addition to the docs sidebar [here](https://learning.postman.com/docs/writing-scripts/pre-request-scripts/).

### Content Type

Video

### If the request is for a video, indicate which type

Exploratory

**Comment by arlemi** [comment]
@claireriley This was released there :D https://www.youtube.com/watch?v=1ls5Dr5SOxw
