### ISSUE TITLE
Content for requesting access to entities, workspaces

### ISSUE THREAD

**Issue by claireriley** [postmanlabs/devrel-content#120]
### Describe the content you'd like to see

I'm having trouble finding video or blog content related to requesting access to entities (APIs, collections, etc) or workspaces that could be included in the sidebar [here](https://learning.postman.com/docs/collaborating-in-postman/requesting-access-to-collections/)

### Content Type

Video, Blog

**Comment by loopDelicious** [comment]
@mjgutermuth are you planning a blog, in addition to the levelup? it might have been an oversight if someone tagged it blog by accident.

**Comment by mjgutermuth** [comment]
Yes @loopDelicious I was planning on doing the levelup first and then a blog
