### ISSUE TITLE
Manage team profile for public APIs

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/devrel-content#121]
### Describe the content you'd like to see

Segmentation examples demonstrating how teams with multiple business units, product lines, and APIs organize their team profile within Postman.
LinkedIn
Intel Sec
Oracle
Meta
Cisco

### Content Type

Blog

**Comment by mjgutermuth** [comment]
Add a link here after this is published: https://www.postman.com/devrel/workspace/developer-experience/overview

**Comment by rebeccajg** [comment]
Heya @mjgutermuth, would be good to sync with Kevin Keene on your thoughts here. He authored a blog earlier this year on team profiles, and optimizing them for SEO that I believe was pretty well received. It may make sense to add onto the existing blog? Would be good to huddle either way.

**Comment by mjgutermuth** [comment]
https://blog.postman.com/5-ways-to-set-up-your-postman-team-profile/
