### ISSUE TITLE
Update existing Supernova Program Landing Page

### ISSUE THREAD

**Issue by jansche** [postmanlabs/devrel-content#130]
### Describe the creation, change or activity you'd like to see

Update the existing page content at [Postman Supernova Program](https://www.postman.com/company/supernovas-program/) to include updated program details. Include A program directory of members and a map.

### Program

Supernova

### If the request is of type Supernova, please categorize further here.

Website

**Comment by Kcorb95** [comment]
Design has been handed off to martech!

**Comment by rebeccajg** [comment]
@Kcorb95 , would love your thoughts -- would it make sense to move this to the backlog for now, while we further explore the Supernovas program?

**Comment by Kcorb95** [comment]
Makes sense!
