### ISSUE TITLE
Source potential Supernova candidates manually

### ISSUE THREAD

**Issue by Kcorb95** [postmanlabs/devrel-content#135]
### Describe the creation, change or activity you'd like to see

Identify and organize 10 potential Supernova candidates that we can reach out to.

### Program

Supernova

### If the request is of type Supernova, please categorize further here.

Promotion

**Comment by Kcorb95** [comment]
Currently organizing through Supernova Airtable

**Comment by jansche** [comment]
@Kcorb95 has identified 8 candidates in Orbit. 

Next step is to reach individually and introduce the program to them. Tracking of that process is in general Supernova Airtable (roster).

**Comment by Kcorb95** [comment]
Contacted the top 3. Will revisit in August for a new wave of invites.
