### ISSUE TITLE
PyCon Kenya social promotion

### ISSUE THREAD

**Issue by jansche** [postmanlabs/devrel-content#139]
### Describe the creation, change or activity you'd like to see

PyCon Kenya. Create some social buzz around our sponsoring of the event.

### Program

Event Sponsorship

### If the request is of type Supernova, please categorize further here.

Promotion

**Comment by Kcorb95** [comment]
I'd like to get something scheduled for this coming week. 

Currently it looks like they do not have anything really substantial on their website to explain what the event is about (beyond just "The Pycon Edition of Kenya brings together software devs, startups, students, learning instutions and people passionate about python and its ecosystem"), when it's taking place besides the 6th and 7th or who is speaking. 

There seem to be typos and grammatical issues still so should we wait for them to update or is there more info? @jansche 
https://www.pyconke.org/

**Comment by Kcorb95** [comment]
Looks like more has been added to the website. I'll have something up for next week

**Comment by Kcorb95** [comment]
<img width="291" alt="image" src="https://user-images.githubusercontent.com/40337763/165997527-a5527f42-2737-4357-8085-dba4a6980017.png">

**Comment by Kcorb95** [comment]
The timer on their website is showing that the event begins at 8 PM EST or 5 PM PST
![image](https://user-images.githubusercontent.com/40337763/166266609-2cb84c3f-fc30-4119-80c0-80d07818365a.png)

**Comment by jansche** [comment]
I think that's because their day (technically) starts then. It's not a countdown to the hour of the opening keynote. But to the 00:00 time of the opening day.
