### ISSUE TITLE
Create DevRel Programs Analytics

### ISSUE THREAD

**Issue by jansche** [postmanlabs/devrel-content#155]
### Describe the creation, change or activity you'd like to see

Work on DevRel analytics for the team's programs to generate insights.
Start with Supernovas and events / CfPs, and work with the team to generate more insights for existing datapoints.

Expected outcome: data insights, predictions, conclusions, indicators  

### Program

Reporting (Trip Reports, CfPs, Speaking)

### Please categorize your Issue by selecting one or more of these types.

Pipeline

**Comment by arlemi** [comment]
Done at the program level for events/livestreams/guest blogs/badges.
