### ISSUE TITLE
Content prep for apidays INTERFACE conference

### ISSUE THREAD

**Issue by jansche** [postmanlabs/devrel-content#158]
### Describe the content you'd like to see

We'll have a workshop at INTERFACE. Ankit Sobti, Fran Mendez and Arnaud Loret will be speaking there as well. 

Please choose someone to prep the workshop and deliver it.

Event Date: June 8&9, 2022
Location: Virtual
Timezone: PST agenda

### Content Type

Workshop

**Comment by arlemi** [comment]
All good to go, I'll be re-using a workshop we had previously developed for Postman Galaxy.
