### ISSUE TITLE
Import HAR file

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/devrel-content#16]
### Is there an existing request for this content?

- [X] I have searched the existing issues for this feature request

### Describe the content you'd like to see

Level up

### Content Type

Video

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arlemi** [comment]
Leaving a comment to test HAR export

**Comment by arlemi** [comment]
Leaving a comment to test HAR export

**Comment by arlemi** [comment]
Leaving a comment to test HAR export

**Comment by arlemi** [comment]
Leaving a comment to test HAR export

**Comment by arlemi** [comment]
Title:  Import a HAR file in Postman

Description: You can now import HTTP Archive (HAR) files directly in Postman. In this video, we'll show you how to create a HAR file if you don't have one, and how to import it as a collection in Postman. 

There are many other file formats you can import to Postman (OpenAPI, GraphQL, cURL...), read more about it in the Learning Center: https://learning.postman.com/docs/getting-started/importing-and-exporting-data/#importing-data-into-postman

Video:
https://user-images.githubusercontent.com/5029719/151782743-5fcbc56f-ffed-4a5f-85ef-8b94ef6cdda6.mp4

**Comment by tobiaswettstein** [comment]
Hello All,

**Comment by tobiaswettstein** [comment]
Here is yt version for review:

**Comment by tobiaswettstein** [comment]
https://youtu.be/E3uo-oQ9WtE

**Comment by arlemi** [comment]
Thank you @tobiaswettstein, looks good! We can switch it to public, and I'll close this issue in the meantime. 👍
