### ISSUE TITLE
How to call Google APIs on Postman

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#164]
### Describe the content you'd like to see

There's a SO answer that demonstrates how to setup Auth for Google APIs on Postman, it's a bit outdated but still used by many people. 
https://stackoverflow.com/questions/32076503/using-postman-to-access-oauth-2-0-google-apis

We need a collection and updated tutorial on how to do so. 

### Content Type

Collection, Tutorial

- [x] Collection - https://github.com/postmanlabs/devrel-content/issues/461
- [x] Blog - https://github.com/postmanlabs/devrel-content/issues/462
- [x] How-to Video - https://github.com/postmanlabs/devrel-content/issues/463
- [x] Quickstarts - https://github.com/postmanlabs/devrel-content/issues/464

**Comment by Gbahdeyboh** [comment]
I splitted this issue into 4 micro issues. 

Collection - https://github.com/postmanlabs/devrel-content/issues/461
Blog - https://github.com/postmanlabs/devrel-content/issues/462
How-to Video - https://github.com/postmanlabs/devrel-content/issues/463
Quickstarts - https://github.com/postmanlabs/devrel-content/issues/464

**Comment by arlemi** [comment]
@Gbahdeyboh Should I close this one then?

**Comment by Gbahdeyboh** [comment]
No, we could leave this open as a task to create multiple learning resources around OAuth in Postman and link all of them together. 

So we can close it out when those other four tasks are completed. What do you think?

**Comment by arlemi** [comment]
That works, I've updated the original post to include them too.

**Comment by Gbahdeyboh** [comment]
Video, Blog, and Quickstarts have been created and are all under review.

**Comment by Gbahdeyboh** [comment]
Blog - https://blog.postman.com/how-to-access-google-apis-using-oauth-in-postman/

Collection - https://www.postman.com/postman/workspace/postman-answers/request/20781379-0e83205d-c07c-431f-b96f-618ed25aa1b3

Video - https://www.youtube.com/watch?v=e-hOP3P-cW8

Quickstarts - https://quickstarts.postman.com/guide/google-oauth-in-postman/index.html?index=..%2F..index#0
