### ISSUE TITLE
Curated list: Databases

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/devrel-content#17]
### Is there an existing request for this content?

- [x] I have searched the existing issues for this feature request

### Describe the content you'd like to see

1. Create a new curated list re: **Databases** (or something else if you prefer) that includes at least these partners:
- https://www.postman.com/mongodb-devrel
- https://www.postman.com/notionhq
- https://www.postman.com/harperdbio
- https://www.postman.com/snowflake
1. **Optional** to include in the intro: https://www.postman.com/postman/workspace/published-postman-templates/collection/5922408-41044117-22a7-4f36-869c-13f73310b7e9
1. **Format** - follow this example: https://blog.postman.com/top-payment-apis-fintech/
2. **Categories** - This is new. You will not need an in-app Postman list in Explore to link to from within the blog. Instead, ask #api-network to create a new category that includes these profiles once the blog has been published.
2. Existing request for blog featured image already with Linda: https://postmanlabs.atlassian.net/jira/core/projects/BE/board?issueKey=BE-57

### Content Type

Blog

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by loopDelicious** [comment]
There's also some cloud storage options that you can add @seanryankeegan - like on cloud platforms.

**Comment by seanryankeegan** [comment]
I've got a draft of this post ready for review. I've asked @arlemi to take a look and get his thoughts. I couldn't find anything worth adding for Amazon/Google/Microsoft/Oracle, so for now it's only the 4 listed in the initial scope of the issue.

**Comment by arlemi** [comment]
Blog post is out 🥳 

https://blog.postman.com/top-database-apis/
