### ISSUE TITLE
Video for external libraries

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#172]
### Describe the content you'd like to see

Need a level up for https://github.com/postmanlabs/devrel-content/issues/2

### Content Type

Video

### If the request is for a video, indicate which type

Level-Up

**Comment by seanryankeegan** [comment]
Video has been recorded and sent to Tobi. He is backed up at the moment, so it might take a bit for him to get to. Raw assets and more info is on row 10 of the internal DevRel video tracker.

**Comment by arlemi** [comment]
Aaaand it's out, thank you @seanryankeegan 🙏 

https://www.youtube.com/watch?v=515xUz1rSNQ
