### ISSUE TITLE
How To : Export & Import

### ISSUE THREAD

**Issue by pmmistry** [postmanlabs/devrel-content#189]
### Describe the content you'd like to see

Video on how to export & import collection

### Content Type

Video

### If the request is for a video, indicate which type

How-To

**Comment by pmmistry** [comment]
**Raw Video Created:**  https://drive.google.com/drive/u/0/folders/1VFsevkWwoL9H08oJEivOLJxSLgEUp2q5 
**Title:** How to Export and Import Data in Postman


**Description :** 
With Postman, you can import and export your data, including collections, environments, data dumps, and globals. Postman can also import non-Postman data in the form of API schemas to help you consolidate your API development workflow.

Importing and Exporting Data: https://learning.postman.com/docs/getting-started/importing-and-exporting-data/

**Comment by arlemi** [comment]
Aaaaand it's out! Good stuff @pmmistry 🥳 

https://www.youtube.com/watch?v=sCWwOzhUMXE
