### ISSUE TITLE
Adding external libraries to Postman

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#2]
### Is there an existing request for this content?

- [X] I have searched the existing issues for this feature request

### Describe the content you'd like to see

We need a collection in Postman Answers that demonstrates how to use external libraries in Postman.

Ideally, we also want a blog post that explains the different ways to do it, and the benefits/drawbacks of each. 

Part of the most frequently asked questions on the community forum:
https://community.postman.com/t/adding-external-libraries-to-postman/1971

### Type of content needed

Collection, Blog

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seanryankeegan** [comment]
Collection is [done](https://www.postman.com/postman/workspace/postman-answers/collection/13455110-7a6c90f0-0062-4089-b206-27c803dc1c37) and blog post [draft](https://docs.google.com/document/d/13UalUCbWc-K1il-UfCxAMiRZYLvtqMOWhxpgywRT7Kk/edit?usp=sharing) is up. Just waiting for feedback on it.

**Comment by seanryankeegan** [comment]
Blog is live! Moving to done :)
