### ISSUE TITLE
Need help in promoting the upcoming Webinar

### ISSUE THREAD

**Issue by Pricilla09** [postmanlabs/devrel-content#208]
### Describe the creation, change or activity you'd like to see

Dear Team,

I will be talking in the upcoming webinar: Unleash the Speaker in You. 

I will be sharing my experiences about this Public Speaking journey, how I started, and how the Supernova program helped me to stay on top of things. Initially, I started giving external talks to get qualified for the Supernova program. But now I am stoppable. I am speaking at various events about APIs, Postman and general Testing topics. 

https://www.airmeet.com/e/82739cf0-d987-11ec-bba3-23965a5c80f0

### Program

Supernova

### Please categorize your Issue by selecting one or more of these types.

Promotion

**Comment by Kcorb95** [comment]
Scheduled two rounds of posts on socials for 7 days and 2 days before :)
<img width="181" alt="image" src="https://user-images.githubusercontent.com/40337763/170805601-57dd8427-32b0-4d6f-8d88-838ea4fb16e0.png">
