### ISSUE TITLE
How To - Release management for APIs

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#21]
### Describe the content you'd like to see

How To videos on release management for APIs

### Content Type

Video

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arlemi** [comment]
@loopDelicious Is it this one? https://www.youtube.com/watch?v=rTTAVlUxfDc

If so feel free to close the issue. 😁

**Comment by loopDelicious** [comment]
It's covered in this one: https://youtu.be/LzJEKsccQ70 I'll mark this issue closed.
