### ISSUE TITLE
Stytch guest blog

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/devrel-content#218]
blog

Passwordless authentication, email magic link, biometrics (fingerprint, voiceprint, or eyeball scan to verify your identity)

**Comment by arlemi** [comment]
@loopDelicious This was published: https://blog.postman.com/go-passwordless-stytch-email-magic-links/

Please have them fill this so we can send them swag: https://airtable.com/shr11fFrUgleN2cjw
