### ISSUE TITLE
Exploratory - Source Control 

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#22]
### Describe the content you'd like to see

A video that highlights how to work with your source control repository in Postman. 

### Content Type

Video

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arlemi** [comment]
@loopDelicious I see we already have this video from John, wasn't sure if this was something different we wanted here: https://www.youtube.com/watch?v=8jJHXLVYOh0

**Comment by loopDelicious** [comment]
Ok - I see issues opened for GitLab and Bitbucket. I'll mark this issue as closed.
