### ISSUE TITLE
Metronome guest post

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/devrel-content#221]
Usage-based billing

https://docs.google.com/document/d/1WVZx6Oa8zpl9PwXQdjiWUWOu9jfy74WrEJh56dkaOOs/edit

Imagery: time-series data, bar graph going up and down over time, financial services (money icon)

**Comment by arlemi** [comment]
All the guest blog posts! 

https://blog.postman.com/usage-based-pricing-model-metronome-postman/
