### ISSUE TITLE
OSCA Day Abuja Event Marketing

### ISSUE THREAD

**Issue by Kcorb95** [postmanlabs/devrel-content#226]
Need posts on social / forums for June 25th event.
https://www.eventbrite.com/e/osca-abuja-open-source-day-tickets-354560870107

We also have [Debo speaking](https://docs.google.com/document/d/1uxGfdbX-ePveIvIuSwYZk1tOsNsdeBXyeAgPJtN46I8/edit?usp=sharing) there.

**Comment by jansche** [comment]
Signed the sponsoring agreement, sent logo package.
