### ISSUE TITLE
Sponsorship and Promotion - Meet-up in KL, Malaysia - API Testing using Postman

### ISSUE THREAD

**Issue by Pricilla09** [postmanlabs/devrel-content#230]
Dear Team,

We are planning for an in-person meet-up in KL by [Synapse QA](https://synapse-qa.com/) 

Topic: API Testing for everyone
This is a beginner's session followed by hands-on using Postman. 

Other details:
Venue: [Triune](https://triune.com.my/)
Date: July 16th, Saturday
Time: 10 AM to 12:30 PM MYT
Projected audience: 35 pax

We are planning to buy Pizza and a few non-alcoholic beverages which cost around $135 (600RM). Kindly approve. 

P.S Planning for Eventbrite registration and will share the link later. 

### Program

Supernova

### Please categorize your Issue by selecting one or more of these types.

Promotion, Operations

**Comment by Pricilla09** [comment]
@jansche and Kevin, Please find the Eventbrite link: https://www.eventbrite.com/e/synapse-qa-meetup-api-testing-for-everyone-tickets-373500689617

**Comment by Kcorb95** [comment]
Posts scheduled!
<img width="184" alt="image" src="https://user-images.githubusercontent.com/40337763/178592075-e6147db6-3fa6-4be5-8308-a6d68bd370cb.png">
