### ISSUE TITLE
JAMStack Meetup co-organizing

### ISSUE THREAD

**Issue by jansche** [postmanlabs/devrel-content#245]
### Describe the creation, change or activity you'd like to see

NYC, July 26
https://www.meetup.com/postman-global-user-group/events/287017915/
and
https://www.meetup.com/JAMstack-nyc/

Co-organising and promoting

### Program

Events

### Please categorize your Issue by selecting one or more of these types.

Operations

**Comment by Kcorb95** [comment]
- [ ] Catering

- [x] Newsletter

In-App Promo:
- [x] 2 weeks before = Wednesday, July 13 - Tuesday, July 26 (including)
 
Learning Center:
- [x] 2 weeks before = Wednesday, July 13 - Tuesday, July 26 (including)
 
Forums Announcement (And Banner?):
- [x] Publish announcement Wednesday, July 13 latest
 
LinkedIn / Twitter / Facebook:
- [x] For Claire's Talk.
- [x] For General Event
- [x] "Last Call" post right before event.
