### ISSUE TITLE
Exploratory / Introduction to the postman app

### ISSUE THREAD

**Issue by iandouglas** [postmanlabs/devrel-content#247]
Exploratory / Introduction to the Postman application per https://postmanlabs.atlassian.net/wiki/spaces/EFDOCS/pages/3899359584/Understand+the+Postman+App to describe different areas of the site for terminology like "workbench" and "context bar"

**Comment by mjgutermuth** [comment]
Title: Navigating the Postman app interface

**Comment by mjgutermuth** [comment]
https://youtu.be/Kr8OVXjzw4k
