### ISSUE TITLE
Super Admin role

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/devrel-content#254]
### Describe the content you'd like to see

Super Admin - Manages everything within a team, including team settings, members, roles, and resources in [public, team, or private workspaces](https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/managing-workspaces/#changing-workspace-visibility). Team members with this role can perform all actions that Admin, Billing, Community Manager, and Developer roles can perform ([Enterprise plans only](https://www.postman.com/pricing)).

### Content Type

Video

### If the request is for a video, indicate which type

Level-Up

**Comment by pmmistry** [comment]
Completed : https://www.youtube.com/watch?v=SbvSAvs0Ii8
