### ISSUE TITLE
Speaking at the upcoming conference - Testμ 2022 by Lambdatest - Reaching for Social media shoutout

### ISSUE THREAD

**Issue by Pricilla09** [postmanlabs/devrel-content#258]
### Describe the creation, change or activity you'd like to see

Testμ is about ‘you’ and the future of testing. I will be talking about the topic "Beyond 200 OK". 

While testing the APIs, we focus on certain universal standards and we miss exploring beyond that. For instance, getting the status code as 200 OK is the expected result and we are happy that the API is up and running. Other than the response codes we need to focus on the headers, response body, response time, and cookies, and there are many other things to be focused on during your API testing process. You need to ensure that the APIs are robust, reliable, scalable, and resilient. Also automating your API tests helps you to test efficiently, and deploy quickly. 

If you are looking to elevate your API Testing process, this is the talk for you. I will be sharing all the lessons and experiences which I gained from my failures. 

It's free and a lot of attendee perks are available. Diverse speakers who run sessions, workshops/tutorials. 
Date: Aug 23 - 25
Event page: https://www.lambdatest.com/testuconf-2022
Speaker page: https://www.lambdatest.com/testuconf-2022/pricilla-bilavendran

![Pricilla Bilavendran](https://user-images.githubusercontent.com/71498483/180991447-aec96cfc-250b-47ae-a3c7-28635fea2017.png)

### Program

Supernovas

### Please categorize your Issue by selecting one or more of these types.

Operations

**Comment by Kcorb95** [comment]
Posts went up!
https://twitter.com/getpostman/status/1557381613478092804
https://www.linkedin.com/posts/postman-platform_conference-listen-to-pricilla-bilavendran-activity-6963147304652484608-sls7?utm_source=linkedin_share&utm_medium=member_desktop_web
