### ISSUE TITLE
How To - Share Postman collections

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#26]
### Describe the content you'd like to see

How To showing the different ways to share Postman Collections: 

- To a team workspace
- To a public workspace
- RIP
- Link
- export json

### Content Type

Video

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pmmistry** [comment]
Assign - @pmmistry

**Comment by arlemi** [comment]
Another way to share is by inviting people from your team

**Comment by pmmistry** [comment]
Completed recording of  Video : https://drive.google.com/drive/u/0/folders/1VFsevkWwoL9H08oJEivOLJxSLgEUp2q5 

Ready for Tobi to edit

**Comment by pmmistry** [comment]
Published Video : https://www.youtube.com/watch?v=b9VlFDlwKvI

**Comment by pmmistry** [comment]
Published Video : https://www.youtube.com/watch?v=b9VlFDlwKvI
