### ISSUE TITLE
Exploratory - Update to existing Collections video

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#27]
### Describe the content you'd like to see

We need to update the now out of date video on Collections in Postman. This one needs to include:

- Benefits of collections
- Use cases (documentation, grouping reqs, sharing, running workflows, test suites)
- Collection variables, using with Env
- Collection-level scripts, execution order
- etc

This should be an Exploratory

### Content Type

Video

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by loopDelicious** [comment]
Related to this video: https://youtu.be/bF8q8wvLs8A

**Comment by Kcorb95** [comment]
I'm working on putting together more detailed requirements before drafting a script and the shot list.
Here are some of my first thoughts, https://docs.google.com/document/d/17QQKXXvFbpiCM-QjyMBzYuzoGVbI-UGvJh0ttxYcGmA/edit?usp=sharing

How in depth are we looking to go with some things? 
For example, we could go into monitors, mocks etc. but do we want to in this video?
What about some of the collaboration stuff?

I'm thinking this should be a bit more surface level and then we could link to the more in-depth videos on things like Joyce's video on mocks and the one I'm working on for working with teams.

**Comment by loopDelicious** [comment]
I provided comments in the gdoc.
