### ISSUE TITLE
Livestream: State of the API 2022 Report

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#279]
### Describe the content you'd like to see

It's a full house as the Postman team weighs in on the current state—and the future—of APIs. The 2022 State of the API report surveyed thousands of developers and API professionals on a range of topics, including their organizations’ development priorities, how they get their work done, and where they see the industry going. Let's review the findings together.

Happening on 2022-09-01T15:00:00.000Z

### Content Type

Video

### If the request is for a video, indicate which type

Livestream

**Comment by pmmistry** [comment]
https://docs.google.com/document/d/1o3lqPhgxXlYJ-KF_luq914HRxzcie2sWLu0sLWSA89U/edit#heading=h.df2dtlyrhzt
