### ISSUE TITLE
Level Up - Create a Postman collection

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#28]
### Describe the content you'd like to see

Short Level Up showing how to get started with collections in Postman

- Create new collection
- Save a request
- Fork an existing collection from PW or RIP to edit

### Content Type

Video

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by loopDelicious** [comment]
FYI - I'm creating a 45-sec level-up on collections to use in an onboarding test. There is some overlap with this video, but not covering the same bullets and different title. The scope as described in this issue is good for a Level-up or can be expanded to an Exploratory.
