### ISSUE TITLE
Exploratory - Working with your team

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#29]
### Describe the content you'd like to see

With the new workspaces we need a new video that shows how to work with your team in Postman.

### Content Type

Video

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kcorb95** [comment]
First draft for video script/shot-list is complete!

Is there anything missing that we'd like to cover here?

https://docs.google.com/document/d/1nYa6DreJYYnYst_IZTQfKHxnCL1o5tEogUYWQX-ZDbo/edit?usp=sharing

**Comment by arlemi** [comment]
@Kcorb95 Looks good! I've left a couple comments on the document directly.

**Comment by Kcorb95** [comment]
Thanks for the feedback! I reached out to Matt Ball as well from the previous video and have added sections to talk about the private API network, sharing and also versioning APIs.
I thiiiink this covers just about everything so I have a script completed and can start filming this week.
https://docs.google.com/document/d/1bpnVdU4zOmkMempMdtKK7fdkrBgDyucfKVgkcK6fxk4/edit?usp=sharing

**Comment by arlemi** [comment]
@Kcorb95 Yep perfect! I've replied to the two questions you had at the end of the document, let me know if there's anything else!

**Comment by loopDelicious** [comment]
Reminder to update the Joined new team transactional email campaign with this video link.

**Comment by mjgutermuth** [comment]
https://www.youtube.com/watch?v=NwT062tYvzs
