### ISSUE TITLE
How to pass array as a parameter

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#3]
### Is there an existing request for this content?

- [X] I have searched the existing issues for this feature request

### Describe the content you'd like to see

We need a collection in Postman Answers that shows how to pass an array as a parameter between requests. This will need to use `JSON.parse` and `JSON.stringify`.

This is part more of the most frequently asked questions on the community forum:
https://community.postman.com/t/how-to-pass-array-as-a-parameter/13673

### Type of content needed

Collection

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seanryankeegan** [comment]
I've got a first stab at [the collection](https://postman.postman.co/workspace/Livestream-practice~775723a9-0ffc-4ed4-8e9c-8b11cc0f8880/collection/13455110-ee594811-f8ff-4f5a-8784-4d0800434655) in a practice workspace. Pinged @arlemi to take a look before pushing it to the Postman Answers public workspace.

**Comment by seanryankeegan** [comment]
@arlemi gave a suggestion and I have now put the collection in the Postman Answers workspace. I have also commented on the community forum thread and marked it as the solution 💪 ✅

Closing this issue.
