### ISSUE TITLE
How To - Deploy an API from OpenAPI

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#30]
### Describe the content you'd like to see

To help promote the API First workflow we need a video that shows how you can deploy an API on AWS API Gateway using Postman.

### Content Type

Video

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arlemi** [comment]
@loopDelicious The video you linked doesn't talk about deploying an API, only testing one that's already running on AWS.

**Comment by loopDelicious** [comment]
@arlemi my bad, Meena did a different AWS one called `Sync API schemas to AWS Gateway` on the deprecated spreadsheet. Is this one the same as that one?

**Comment by Kcorb95** [comment]
Are we looking for this to be a level up or something entirely different? I imagine it could be a shorter video similar to the one Joyce linked.

**Comment by arlemi** [comment]
Closing this one as a duplicate of #54
