### ISSUE TITLE
Exploratory on Governance

### ISSUE THREAD

**Issue by iandouglas** [postmanlabs/devrel-content#308]
### Describe the content you'd like to see

What is governance, and free features, with mention (not demo) of enterprise features

### Content Type

Video

### If the request is for a video, indicate which type

Exploratory

**Comment by pmmistry** [comment]
Governance Video Assets : https://drive.google.com/drive/u/0/folders/1YSqPmb_49A99RPFHkPpEDPPKmtrlOHoR
