### ISSUE TITLE
Speaking in the upcoming TestFlix 2022 conference about the Performance Testing of APIs

### ISSUE THREAD

**Issue by Pricilla09** [postmanlabs/devrel-content#313]
### Talk Outline

APIs are transforming the world at an increasing pace. Every day several APIs are developed and adapted based on the needs of the organizations. With the usage of these APIs, developers can create quality applications.
As a Tester, you might be covering the exhaustive functional Testing of your APIs.

Your APIs might be working as designed on a normal day. How about there’s a sale or any worldwide changes which cause an unexpected number of API calls? Probably your APIs should handle it. But will it work? That’s why we need performance testing.

An inefficient API could lead to a slow-running application and will lose potential users. Most performance problems revolve around speed, response time, load time, and poor scalability. Speed is often one of the most important attributes of an API.

Some might be wondering what are tools available for performance testing of our APIs. There are plenty of tools available. I will be demonstrating a few important types of performance testing to be done for your APIs before moving into Production.

### Details:

When? October 8 and 9th

Register using the link: https://bit.ly/3epIuoK

![TF22-IAmSpeaking-R1-Pricilla](https://user-images.githubusercontent.com/71498483/188837532-40dd7d4f-4a8b-4522-ad8b-144bab8e5bb1.png)

### Program

Supernovas

**Comment by Kcorb95** [comment]
Posts scheduled!
