### ISSUE TITLE
TestBash Bucks Marketing

### ISSUE THREAD

**Issue by Kcorb95** [postmanlabs/devrel-content#334]
### Describe the creation, change or activity you'd like to see

Date: Oct 14
URL: https://www.ministryoftesting.com/events/testbashx-buckinghamshire-2022

- [x] Forums
- [x] Socials
- [x] LC

### Program

Events

### Please categorize your Issue by selecting one or more of these types.

Operations

**Comment by arlemi** [comment]
Forum done ✓
