### ISSUE TITLE
Postman Livestream - Test-driving Postman v10

### ISSUE THREAD

**Issue by Kcorb95** [postmanlabs/devrel-content#335]
### Describe the content you'd like to see

Date: Sept 22
URL: https://www.youtube.com/watch?v=9cZlAS-QTuc

Have you heard about Postman v10 yet? In this week's livestream, Postman Community Manager, Kevin Corbett has invited Technical Enablement Architect, Carson Hunter and Senior Developer Advocate, Ian Douglas to explore some of the latest changes in Postman v10.
Learn about changes to testing, API production/consumption and more!

### Content Type

Video

### If the request is for a video, indicate which type

Livestream

**Comment by arlemi** [comment]
@Kcorb95 We have issues being created automatically for livestreams from Airtable, e.g. #319 for this one. I'll add the URL to the stream in the issue though!
