### ISSUE TITLE
DevRel Automations

### ISSUE THREAD

**Issue by Kcorb95** [postmanlabs/devrel-content#338]
### Describe the creation, change or activity you'd like to see

There are many things that we do pretty routinely that can be either automated or need reminders. 
Here's a list and the progress on them:

- [x] Livestream setup & marketing status reminders
- [x] Space Camp almost here and there's no future Space Camp link ready 😴
- [x] We have no streams planned and it's nearly the end of the month
- [x] A stream has ended and it's time to do chapter notes
- [x] A stream has ended and it's still time to do chapter notes (every day for 3 days following event)

### Program

Other Programs

### Please categorize your Issue by selecting one or more of these types.

Operations

**Comment by arlemi** [comment]
I believe most of these are done now right @Kcorb95?
