### ISSUE TITLE
Sentry meetup Q2

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/devrel-content#344]
### Describe the creation, change or activity you'd like to see

Meetup re: API, security, or devops
API tracing
Geo and date: TBD

### Program

Events

### Please categorize your Issue by selecting one or more of these types.

Sourcing

**Comment by loopDelicious** [comment]
Dusting this off again.

**Comment by iandouglas** [comment]
Initial meeting on Friday June 2nd 2023 for planning
