### ISSUE TITLE
Salesforce case study - APIs at Scale for a Great Developer Experience

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/devrel-content#349]
### Describe the content you'd like to see

Case study about how Salesforce uses Postman for developer experience

The story in this video (https://youtu.be/3Ce3AFKp1ck) is still up to date. Philippe can review the draft and provide a pulled quote (if needed, can also use quotes from the video).

CTA is https://www.postman.com/salesforce-developers/workspace/salesforce-developers

### Content Type

Blog

**Comment by mjgutermuth** [comment]
https://blog.postman.com/how-salesforce-shares-apis-at-scale-great-developer-experience/
