### ISSUE TITLE
Setup a developer resource microsite for the learning center

### ISSUE THREAD

**Issue by Gbahdeyboh** [postmanlabs/devrel-content#355]
### Describe the content you'd like to see

This is a developer resource microsite that will host the documentation for the collection format, its toolings, developer resources, and teacher/learning kits for folks speaking/teaching about postman.

### Content Type

Documentation, Tutorial

### If the request is for a video, indicate which type

Other

**Comment by rebeccajg** [comment]
Heya @Gbahdeyboh , is this a request from the Tech Writing team? If yes, let's chat with Jon and support it. If not, I think we can defer this for awhile.

**Comment by Gbahdeyboh** [comment]
No @rebeccajg, it wasn't a request from the Tech Writing team. I'll go ahead and close this.
