### ISSUE TITLE
Azure integration

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/devrel-content#361]
### Describe the content you'd like to see

How-to (~5-10 minutes) 

shorter the better, by abstracting parts that are not integration-specific

### Content Type

Video

- [ ] #425

- [ ] #426

### If the request is for a video, indicate which type

How-To

**Comment by pmmistry** [comment]
Creating two how to videos 

1. How To - Import and Export from Azure API Management to Postman

2. How To - Deploy from Postman to Azure API Management

**Comment by pmmistry** [comment]
Currently in Review with Toby
