### ISSUE TITLE
GitLab integration

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#42]
### Describe the content you'd like to see

With the new integrations in the API Builder, we need one showing how to set up the GitLab one

### Content Type

Video

### If the request is for a video, indicate which type

How-To

**Comment by iandouglas** [comment]
I made a video to coincide with https://learning.postman.com/docs/integrations/available-integrations/gitlab/ by mistake, but hey we have a video for that page now too if we want it.

For THIS story, I built a simple repo at GitLab, import it into postman, and sync it back to to GitLab. I've sent the videos to Tobi.

**Comment by arlemi** [comment]
I mean... we're not going to complain about having too much content! 😄 

Once the videos are out you can let the tech writers know by opening an issue on their repo so they can add it to the sidebar where needed: https://github.com/postmanlabs/postman-docs/issues
