### ISSUE TITLE
How to choose asynchronous APIs

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/devrel-content#421]
### Describe the content you'd like to see

HTTP polling
RPC
WebSockets

Similar to this post: https://blog.postman.com/how-to-choose-http-or-grpc-for-your-next-api/
Related to this post: https://blog.postman.com/understanding-asynchronous-apis/, except diving into which type of API to use per use case or conditions

### Content Type

Blog

### If the request is for a video, indicate which type

None

**Comment by iandouglas** [comment]
given to Pooja and Melinda for review

**Comment by iandouglas** [comment]
being published this week, so closing the ticket
