### ISSUE TITLE
GraphQL in Postman

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/devrel-content#422]
### Describe the content you'd like to see

- [x] Update (and deprecate) this video: https://youtu.be/7pUbezVADQs
- [x] Update video link if embedded in existing blog posts
- [x] Update link in docs

Level-Up videos:
- [x] How to make a GraphQL request in Postman
- [x] How to edit a GraphQL query
- [x] Different types of introspection for GraphQL

Target: 3-4 minutes
Standalone playlist with higher production value, super high res screencapture and face capture.
Coordinate with Tobi the creative direction of face-only portions (to be included in 4K playlist, and also play as non-subscribed channel trailer)

### Content Type

Video

### If the request is for a video, indicate which type

Other

**Comment by pmmistry** [comment]
In review with Tobi

**Comment by pmmistry** [comment]
4K video assets
Intro  ( i took two takes, i’ll let you decide which one you think is the best )
(take1) https://drive.google.com/drive/u/0/folders/1Vxvs9BLn_Vhkcj-VeC3cJdbn3HL56QDS
(take 2) https://drive.google.com/drive/u/0/folders/1Vxvs9BLn_Vhkcj-VeC3cJdbn3HL56QDS
Screen share video : https://drive.google.com/drive/u/0/folders/1Vxvs9BLn_Vhkcj-VeC3cJdbn3HL56QDS
Outro : https://drive.google.com/drive/u/0/folders/1Vxvs9BLn_Vhkcj-VeC3cJdbn3HL56QDS
Video Description : https://docs.google.com/document/d/1nJZQipA9NfF5gAFbwHFlb-SKtD9xP_JjTf1c6X8JSOg/edit

Level-Up : Creating GraphQL Requests
Video : https://drive.google.com/drive/u/0/folders/1UhUYzvdGPPBx4h73_xYcEHOzU7fR1C2x
Description : https://docs.google.com/document/d/1LV-wFDMqXIht2TbXBeBKscJad7fwjnp-pOKKb9gczYI/edit?usp=sharing

Level-Up: Editing GraphQL Queries
Video: https://drive.google.com/drive/u/0/folders/1UhUYzvdGPPBx4h73_xYcEHOzU7fR1C2x
Description : https://docs.google.com/document/d/1H1C9EqTVjsg1TQoUriZqPXuK2SGhMnndDyDWr9cmmE8/edit

Level-Up: Loading GraphQL Schemas
Video : https://drive.google.com/drive/u/0/folders/1UhUYzvdGPPBx4h73_xYcEHOzU7fR1C2x
Description : https://docs.google.com/document/d/1xZvCLeD9nD1nNR3mSVreIWlK8zJXoQygLeXYwL18Fkk/edit
