### ISSUE TITLE
Freelance tutorials: PHP Laravel, Symfony, MySQL, MongoDB, Python

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/devrel-content#467]
### Describe the content you'd like to see

- [x] Build a PHP REST API server with the Laravel Framework
- [x] Build a PHP REST API server with the Symfony Framework
- [x] Build a REST ToDo API with OpenAPI, Node, and MySQL
- [x] Build a REST ToDo API with OpenAPI, Node and MongoDb
- [x] Set up a WebSockets server with Python

### Content Type

Tutorial, Quickstart

### If the request is for a video, indicate which type

None

**Comment by loopDelicious** [comment]
Quickstarts published. 

To syndicate 1 on Postman wordpress blog, and 1 on Postman's dev.to blog @mjgutermuth

**Comment by loopDelicious** [comment]
@mjgutermuth do you have an ETA for syndication?

**Comment by mjgutermuth** [comment]
@loopDelicious one is ready for Greg to review, and the other will be ready later today

**Comment by mjgutermuth** [comment]
Scheduled to publish on Postman blog and dev.to on 6/6

**Comment by mjgutermuth** [comment]
https://blog.postman.com/build-an-api-with-postman-node-js-and-mysql/

**Comment by mjgutermuth** [comment]
https://dev.to/postman/create-a-rest-api-with-php-and-laravel-2gcb

**Comment by mjgutermuth** [comment]
Notes:

- dev.to post looks like it led to a spike in traffic to dev.to/postman (~70 views vs usual ~20), gained 1 new follower, got 2 likes and 4 saves
- Postman blog post got 503 views with 6 likes and a 58% bounce rate

@loopDelicious was there any other comparison you wanted to do on these before I close this?

**Comment by mjgutermuth** [comment]
In a quick look at the top 500 blog post views in the past day (8 days after publishing), it ranked number 70 with 32 views.
