### ISSUE TITLE
Guest user role - levelup

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/devrel-content#478]
### Describe the content you'd like to see

related videos: share link https://youtu.be/tw7x3yBpU1Y, share collections https://youtu.be/b9VlFDlwKvI

Keep it evergreen (do not date the video by announcing a "new" feature)

### Content Type

Video

### If the request is for a video, indicate which type

Level-Up

**Comment by mjgutermuth** [comment]
https://youtu.be/pRIG0Ujphoc
