### ISSUE TITLE
Livestream: A Guide to the Postman Collection Format: Building Collections With JSON

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#495]
### Describe the content you'd like to see

Learn about the Postman Collection format, a specification that forms the basis of collections in Postman. A single collection file contains everything that makes up your collection in Postman and can be used to generate both client and server-side code for your APIs in any programming language, generate documentation and other API specifications.

Happening on 2023-03-16T15:00:00.000Z

### Content Type

Video

### If the request is for a video, indicate which type

Livestream

**Comment by Gbahdeyboh** [comment]
Watch the stream here - https://www.youtube.com/watch?v=Kb8VwUr45QE
