### ISSUE TITLE
Compare 2 responses using Postman

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#5]
### Is there an existing request for this content?

- [X] I have searched the existing issues for this feature request

### Describe the content you'd like to see

We need a collection in Postman Answers that shows how to compare two responses using Postman, as shown in this topic https://community.postman.com/t/compare-2-responses-using-postman/1638

### Type of content needed

Collection

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seanryankeegan** [comment]
Done! Collection available [here](https://www.postman.com/postman/workspace/postman-answers/documentation/13455110-7954de36-7b03-4ea6-989b-8f195a7c5db1).
