### ISSUE TITLE
Configure vale for quickstarts repo

### ISSUE THREAD

**Issue by mjgutermuth** [postmanlabs/devrel-content#507]
### Describe the content you'd like to see

Add [vale](https://vale.sh/docs/vale-cli/overview/) (for prose linting) to the [quickstarts repo](https://github.com/loopDelicious/pmquickstarts/actions) as a GitHub action.

There should be some consistency with the Learning Center's rules, but minor differences are fine as needed. The styles they use are in [postman-docs](https://github.com/postmanlabs/postman-docs/tree/develop/vale-styles) (but they run vale locally, not as a GitHub action).

### Content Type

Quickstart

### If the request is for a video, indicate which type

None

**Comment by loopDelicious** [comment]
Related to this issue in separate repo: https://github.com/loopDelicious/pmquickstarts/issues/28

**Comment by mjgutermuth** [comment]
https://github.com/loopDelicious/pmquickstarts/commit/21cb17dd57b8f3f52c5e130822149ec3d7c456d5
