### ISSUE TITLE
Livestream: Exploring OWASP Top 10: Securing Your APIs With Postman

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#529]
### Describe the content you'd like to see

Improve the security of your APIs with Postman in this week's Postman LIVE as Ian invites Postman security engineers, Rahul Dhawan and Yash Mehta to discuss the OWASP top 10. Learn more about the proposed changes coming for 2023 involving authentication and authorization and what this means for securing your APIs.

Happening on 2023-04-20T15:00:00.000Z

### Content Type

Video

### If the request is for a video, indicate which type

Livestream

**Comment by iandouglas** [comment]
Chapter notes are published
