### ISSUE TITLE
Post-Marketing Workflow for DevRel Content

### ISSUE THREAD

**Issue by Kcorb95** [postmanlabs/devrel-content#531]
### Describe the creation, change or activity you'd like to see

This includes content produced by DevRel including:
- Livestreams
- Videos (Level Up, Exploratory, How To)
- Webinars
- Blog Posts
- QuickStarts
- Supernova Contributions

We're looking for a cadence of ~6 months of social posts, sharing once per month. The end goal is to have two posts per-week where we share older content.

Will be utilizing content gap analysis board as it already picks up all content produced by Postman.

### Program

Other Programs

### Please categorize your Issue by selecting one or more of these types.

Operations

**Comment by Kcorb95** [comment]
Initial version implemented for videos/livestreams/webinars and quickstarts!
![image](https://user-images.githubusercontent.com/40337763/231846827-78dcd6bb-ee5d-4def-a264-c66049aa87d0.png)

**Comment by arlemi** [comment]
@Kcorb95 if you need new labels to be added let me know! e.g. `marketing` or something
