### ISSUE TITLE
Migrate Glitch apps to Heroku

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/devrel-content#538]
### Describe the creation, change or activity you'd like to see

- [x] We have a few apps related to Postman badges running on Glitch. Migrate these apps to Heroku
- [x] Consider hosting them on custom domains (Postman has a long list of domains we manage) to streamline future migrations
- [ ] Update the URL for Postman badges / training

#### Apps to Migrate
- [x] [galaxy-api-adoption](https://glitch.com/edit/#!/galaxy-api-adoption)
- [x] [galaxy-apis-101](https://glitch.com/edit/#!/galaxy-apis-101)
- [x] [postman-skill-checker](https://glitch.com/edit/#!/postman-skill-checker)
- [x] [api-101](https://glitch.com/edit/#!/api-101)
- [ ] [postman-test-checker](https://glitch.com/edit/#!/postman-test-checker)
- [ ] [postman-student-expert](https://glitch.com/edit/#!/postman-student-expert)

### Please categorize your Issue by selecting one or more of these types.

Operations

**Comment by Gbahdeyboh** [comment]
Here's a checklist of all the apps we have on Glitch. Included it in the description of this issue. It'll be checked once worked on. 

- [ ] [galaxy-api-adoption](https://glitch.com/edit/#!/galaxy-api-adoption)
- [ ] [galaxy-apis-101](https://glitch.com/edit/#!/galaxy-apis-101)
- [ ] [postman-skill-checker](https://glitch.com/edit/#!/postman-skill-checker)
- [ ] [api-101](https://glitch.com/edit/#!/api-101)
- [ ] [postman-test-checker](https://glitch.com/edit/#!/postman-test-checker)
- [ ] [postman-student-expert](https://glitch.com/edit/#!/postman-student-expert)
- [ ] [selective-shining-zebu](https://glitch.com/edit/#!/selective-shining-zebu)
- [ ] [dust-light-wire](https://glitch.com/edit/#!/dust-light-wire)
- [ ] [nebulous-spicy-clove](https://glitch.com/edit/#!/nebulous-spicy-clove)

**Comment by Gbahdeyboh** [comment]
We have a postman.training domain. Each glitch app here can be a sub domain on that domain. e.g `galaxy-api-adoption.postman.training`, `galaxy-apis-101.postman.training`, etc.
