### ISSUE TITLE
How to Templates for collections and workspace

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#544]
### Describe the content you'd like to see

Need a video for templates in workspaces and collections (April and May releases)

### Content Type

Video

### If the request is for a video, indicate which type

How-To

**Comment by mjgutermuth** [comment]
oops I just realized this was supposed to be a How To. I made a Level Up: https://www.youtube.com/watch?v=QAIH1D203Wg

**Comment by arlemi** [comment]
@mjgutermuth Looks like you managed to fit all the info required anyway, good stuff! 👏
