### ISSUE TITLE
Create blog post on using Twitch API to make a Slack bot

### ISSUE THREAD

**Issue by Kcorb95** [postmanlabs/devrel-content#55]
### Describe the content you'd like to see

In addition to my first collection, I would like to create a blog post documenting my process in making a slack integration that helps you find content on Twitch.
Somewhat of a similar spin as this https://blog.postman.com/building-a-bot-for-busy-gamers/
Some key points would be how to handle refreshing your oauth token

### Content Type

Collection, Blog

**Comment by arlemi** [comment]
We might need to get you on the livestream to demo it too... 👀

**Comment by Kcorb95** [comment]
Draft is ready! 
https://docs.google.com/document/d/101lmvHJU-muFK0BUmbNv0b2qhRvQXEyQbaIEJQe8PVw/edit?usp=sharing
