### ISSUE TITLE
Speaking in the upcoming AgileTDUSA 2023 conference - API Testing for Everyone workshop

### ISSUE THREAD

**Issue by Pricilla09** [postmanlabs/devrel-content#550]
### Describe the creation, change or activity you'd like to see

APIs are changing the world at a rapid pace. Every day, several APIs are created and adapted to meet the needs of organizations. Developers can create high-quality applications by utilizing these APIs. One of the major reasons for the increased focus on API Testing is the rise of API-First companies. It is now included in nearly every job description for Testers. During the API testing process, there are numerous other aspects to pay attention to in addition to the fundamental headers and response validation. I have to spend some time exploring and unlocking these regions. I'll give a broad overview, beginning with the API testing strategy and ending with the specific validations carried out. You must make sure that the APIs are stable, dependable, scalable, and resilient in addition to the typical validations. Without this understanding, any API Testing trip would be at risk, which would cause a Ripple effect. Have no fear; we've got you. A few best practices, good testing methodology, and strong API knowledge can work miracles! Integration and regression testing are made easier by automating APIs. Additionally, it shortens the time required for feedback, patches, and redeployments during execution. As a result, the applications are more scalable, resilient, and reliable. Automated API testing must be done in-depth and thoroughly to assure the high quality of software applications. Most of us likely have a rudimentary idea of how APIs work by this point. For the most part, we would have begun API testing for your applications. A few best practices, aside from simple API validations, could aid in seamless API testing and automation. The output that is needed requires the integration of multiple programs. Different applications can be integrated for various use cases, leading to the end-to-end control of the API life cycle. Let's support the creation of high-quality APIs by the developers, which will lead to high-quality applications. This session is for you if you want to improve your API testing process. I'll be discussing all the knowledge and insights I've gathered from my failures.

Details:
When? May 23rd and 24th

Register using the link: https://agiletestingdays.us/register/

Full program details: https://agiletestingdays.us/program/

### Program

Supernovas

### Please categorize your Issue by selecting one or more of these types.

Operations, Sourcing

**Comment by Pricilla09** [comment]
https://www.linkedin.com/company/agile-testing-days-usa/

**Comment by Kcorb95** [comment]
Posts are scheduled! Thanks @Pricilla09 and good luck :)
![image](https://github.com/postmanlabs/devrel-content/assets/40337763/d726ddfd-1a50-4685-a689-cabd1d77b8c4)
![image](https://github.com/postmanlabs/devrel-content/assets/40337763/5750ca20-0fbe-41a3-951e-f79a45121fc1)
![image](https://github.com/postmanlabs/devrel-content/assets/40337763/3fdf36b2-f46d-4f74-a771-db2f43e1ef35)
