### ISSUE TITLE
Livestream: How To Begin Securing Your API for Authorization

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#556]
### Describe the content you'd like to see

In this week's Postman LIVE, Ian has invited Postman Supernova Orest Danylewycz, Information Security Engineer from Westfield Insurance to help dissect an insecure API, shining a spotlight on one of the critical warnings from OWASP's API Top Ten: insecure data access. Through this hands-on exploration, learn practical techniques to secure your API, ensuring it only provides access to authorized data.

Happening on 2023-06-01T15:00:00.000Z

### Content Type

Video

### If the request is for a video, indicate which type

Livestream

**Comment by iandouglas** [comment]
also wrote some code as well, https://github.com/postmanlabs/livestream-content/tree/main/owasp-bola
