### ISSUE TITLE
Unboxing Q2 Intergalactic Session - July 

### ISSUE THREAD

**Issue by pmmistry** [postmanlabs/devrel-content#561]
### Describe the content you'd like to see

Unboxing Q2 Postman Intergalactic Session 

### Content Type

Video

### If the request is for a video, indicate which type

None

**Comment by arlemi** [comment]
@pmmistry Issues for Intergalactic and Livestreams are automatically created from Airtable, let's use these instead. 

For Intergalactic this happens when you tick the "Ready for Marketing" box. ✅
