### ISSUE TITLE
Livestream: API Playground: A Hands-on Challenge with IoT and Postman Flows

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#572]
### Describe the content you'd like to see

In this week's Postman LIVE, join technical community manager, Kevin Corbett as he challenges senior developer advocate, Ian Douglas to build API requests in Postman to fetch weather data and manipulate the color of his IoT-connected smart lights based on the temperature. But the challenge doesn't end there - Ian flips it back to Kevin, pushing him to work with these API requests using Postman Flows. Tune in to see how API requests can become the building blocks in Postman Flows, a visual tool for constructing API-driven applications.

Happening on 2023-06-15T15:00:00.000Z

### Content Type

Video

### If the request is for a video, indicate which type

Livestream

**Comment by Kcorb95** [comment]
https://youtu.be/Jw2ArXvxc4U
