### ISSUE TITLE
Livestream: A Few JSON Schema Tips & Tricks: Getting Started

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#585]
### Describe the content you'd like to see

In their debut Postman LIVE, Postman technical writer, Melinda Gutermuth is joined by Ian as they invite API specifications tech lead, Julian Berman to discuss JSON Schema best practices. Dive into the world of JSON Schema, as they explore its use cases in OpenAPI, AsyncAPI, and beyond. Uncover crucial tips and tricks while traversing topics from versioning to types, conditional schema applications, and even validation. Whether you're a beginner or experienced with JSON Schema, this session promises a wealth of knowledge and practical insights.

Happening on 2023-06-29T15:00:00.000Z

### Content Type

Video

### If the request is for a video, indicate which type

Livestream

**Comment by mjgutermuth** [comment]
https://www.youtube.com/watch?v=QiAXxaLrt7E

**Comment by arlemi** [comment]
@mjgutermuth Can one of you add the chapter notes please? 🙏
