### ISSUE TITLE
Consuming My First REST API

### ISSUE THREAD

**Issue by pmmistry** [postmanlabs/devrel-content#587]
### Describe the content you'd like to see

Translate this to something more hands-on and visual: https://blog.postman.com/rest-api-examples/

### Content Type

Video

### If the request is for a video, indicate which type

How-To

**Comment by rebeccajg** [comment]
Heya @pmmistry , on this task, it'd be good to sync with Kevin Keene on SEO opportunities here. One of the things we've learned is that in some places, where we can combine a blog or a webpage with a supporting video on the same page, the content is really helping folks who are looking to learn that topic.
