### ISSUE TITLE
Unboxing July Intergalactic 

### ISSUE THREAD

**Issue by pmmistry** [postmanlabs/devrel-content#590]
### Describe the content you'd like to see

Intergalactic Session with Arlemi : https://www.postman.com/events/intergalactic/unboxing-whats-new-q2/july-2023/ 

### Content Type

Video

### If the request is for a video, indicate which type

Livestream

**Comment by arlemi** [comment]
There is an automation that creates these issues from Airtable when you tick the "Ready for Marketing" box. 

Edit: I've triggered it this time, cf #592
