### ISSUE TITLE
15 days of Postman - for testers

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/devrel-content#61]
### Describe the content you'd like to see

✅ Workspace
✅ Blog re: 15 days - submitted for review
✅ Video
✅  Hiring matrix
✅  Blog re: Postman skills hiring matrix - submitted for review
✅ Badge
✅ TikTok series
- Video re: Postman skills hiring matrix

### Content Type

Collection, Video, Blog

**Comment by arlemi** [comment]
@loopDelicious Do we want to add these to the issue creation template?
- Hiring matrix
- Badge
- TikTok

**Comment by loopDelicious** [comment]
My 2 cents is no - I anticipate they are infrequent or exclusive to me.

**Comment by arlemi** [comment]
[ ] test
[ ] test2
