### ISSUE TITLE
Intergalactic: gRPC

### ISSUE THREAD

**Issue by iandouglas** [postmanlabs/devrel-content#617]
### Describe the content you'd like to see

Expanding from the livestream earlier in 2023, putting together an intergalactic session on how to design and test/mock a gRPC API within Postman

### Content Type

Tutorial, Workshop

### If the request is for a video, indicate which type

Other

**Comment by loopDelicious** [comment]
Sept 27

**Comment by iandouglas** [comment]
Outline given to Joyce and Udit for review
