### ISSUE TITLE
Livestream: Mastering API Performance Testing with Postman

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#618]
### Describe the content you'd like to see

In this week's Postman LIVE, Ian invites Postman's Senior Solutions Architect, John Banning, to unpack and discuss the new API Performance Testing feature in Postman. Dive into code optimization best practices and engage in a lively discussion, sharing your most effective strategies for refining API performance.

Happening on 2023-08-10T15:00:00.000Z

### Content Type

Video

### If the request is for a video, indicate which type

Livestream

**Comment by iandouglas** [comment]
youtube chapter notes done
