### ISSUE TITLE
Create content for scratchpad

### ISSUE THREAD

**Issue by claireriley** [postmanlabs/devrel-content#65]
### Describe the content you'd like to see

We currently don't have any content for the sidebar on [Using the Scratch Pad](https://learning.postman.com/docs/getting-started/using-scratch-pad/). Not sure what type of content would be most useful, but maybe a brief Level Up video or blog post?

### Content Type

Video

### If the request is for a video, indicate which type

Other

**Comment by sahuvikramp** [comment]
Live on YouTube : 

[![accessing the scratchpad](https://i.ytimg.com/vi/AHpdO8AetjA/hqdefault.jpg?sqp=-oaymwEcCPYBEIoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAOgy-txx3J608vKMi4TCwyOdkYgQ)](https://www.youtube.com/watch?v=AHpdO8AetjA)

**Comment by sahuvikramp** [comment]
Importing data from scratchpad on YouTube :

[![importing data from the scratchpad](https://i.ytimg.com/an_webp/GZWf7F-aVDc/mqdefault_6s.webp?du=3000&sqp=CPftrZEG&rs=AOn4CLAvEXFyph-WSv51VxkLeylba04YlA)](https://youtu.be/GZWf7F-aVDc)

**Comment by sahuvikramp** [comment]
Hence, closing the ticket.
