### ISSUE TITLE
Update workspaces blog

### ISSUE THREAD

**Issue by claireriley** [postmanlabs/devrel-content#66]
### Describe the content you'd like to see

[This blog](https://blog.postman.com/workspaces-the-biggest-thing-to-hit-postman-this-month/) has some great info for new users and growing teams, but is outdated (mentions sharing vs moving, has an unlisted video embedded). An updated version would be a nice addition to the sidebars on [Creating a workspace](https://learning.postman.com/docs/getting-started/creating-your-first-workspace/) and [Creating workspaces](https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/creating-workspaces/).

### Content Type

Blog

**Comment by Linda-Koffman** [comment]
Hey @arlemi, do you need an image for this for end of July or later?

**Comment by arlemi** [comment]
@Linda-Koffman End of July would be great! 🙏

**Comment by arlemi** [comment]
Using this already: https://blog.postman.com/solving-problems-together-with-postman-workspaces/
