### ISSUE TITLE
Crypto.js code sample in Postman Answers

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/devrel-content#70]
### Describe the content you'd like to see

`crypto` and `cryptojs` are popular zero-search result terms in the Learning Center. The library is included in [the sandbox docs](https://learning.postman.com/docs/writing-scripts/script-references/postman-sandbox-api-reference/), but not indexed in the docs search due to a known limitation. There are also various [questions on the community forum](https://community.postman.com/search?q=crypto) around usage of this library.

Include a code sample of various use cases with CryptoJS in [Postman Answers public workspace](https://www.postman.com/postman/workspace/postman-answers/overview). Can include code provided in [this reference](https://postman-quick-reference-guide.readthedocs.io/en/latest/libraries.html) for Crypto.

### Content Type

Collection, Tutorial (blog that links to collection), Level-Up video

### If the request is for a video, indicate which type

Level-Up

**Comment by sahuvikramp** [comment]
The document and collection link is shared with @seanryankeegan and @iandouglas. Once review and proofreading is done, we can move it to the next bucket.

**Comment by sahuvikramp** [comment]
The blog is published: [Cryptography](https://blog.postman.com/what-is-cryptography-how-to-encrypt-data-in-postman/) 
How to video has been submitted to Tobi

**Comment by sahuvikramp** [comment]
Video released on YouTube  

[![cryptography](https://i.ytimg.com/vi/W_Gj1Q0lEOU/hq720.jpg?sqp=-oaymwEcCNAFEJQDSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLAT80t8a-OXD8EAm4N9EgKPwQQRKg)](https://youtu.be/W_Gj1Q0lEOU)
