### ISSUE TITLE
Infobip meetup talk :: April 11, 2022

### ISSUE THREAD

**Issue by seanryankeegan** [postmanlabs/devrel-content#76]
### Describe the content you'd like to see

On April 11th, Infobip is hosting a [meetup in NYC](https://www.meetup.com/infobip-developers/events/283710356/). There is a 20-minute slot for a Postman presentation/demo. I plan on speaking at this. Exact content TBD. @loopDelicious is creating a reusable talk that I may repurpose for this presentation.

### Content Type

Talk

**Comment by arlemi** [comment]
Closing as this is passed and we ended up not participating.
