### ISSUE TITLE
Infobip meetup talk :: April 14, 2022

### ISSUE THREAD

**Issue by seanryankeegan** [postmanlabs/devrel-content#78]
### Describe the content you'd like to see

On April 14th, Infobip is hosting a [meetup in NYC](https://www.meetup.com/infobip-developers/events/283710372/). There is a 20-minute slot for a Postman presentation/demo. Sean will not be able to attend this one, so this is an open slot up for grabs. @loopDelicious is creating a reusable talk that may be repurposed for this presentation.

### Content Type

Talk

**Comment by loopDelicious** [comment]
Related to this issue: https://github.com/postmanlabs/devrel-content/issues/56

**Comment by arlemi** [comment]
Closing this one as we are not taking part in it. We're tracking the content creation in #56 and another infobip event in #77.
