### ISSUE TITLE
CROSSKNOT Hackathon

### ISSUE THREAD

**Issue by sahuvikramp** [postmanlabs/devrel-content#79]
### Describe the content you'd like to see

36 hours hackathon where I would like to create a combined collection on different tracks which includes : 

1. cyberbullying.
2. Automation for developers. 
3. Open innovation
4. Blockchain 
5. Remote world hiring, work, and learning.
6. Mental health
7. No code solution.

Goals 🎯

- Usability of postman.  
- Collection that can be used in any hackathon.
- Saving candidate's time (API readily available, code-snippets, low-code or no code way)

### Content Type

Collection, Talk, Workshop

**Comment by arlemi** [comment]
Too short notice to provide support for it, they'll reach out earlier next year (hopefully 🤞)!
