### ISSUE TITLE
How to test properties and arrays correclty

### ISSUE THREAD

**Issue by arlemi** [postmanlabs/devrel-content#8]
### Is there an existing request for this content?

- [X] I have searched the existing issues for this feature request

### Describe the content you'd like to see

There are many ways to test array properties, it'd be great to have a collection that shows an overview of the different things that can be tested (existence of a key, type...), as outlined in that post: https://community.postman.com/t/testing-properties-and-arrays-correctly-in-get/7133

It'd also be great to have a blog highlighting the different ways to do so that redirects to that same collection as a demo.

### Type of content needed

Collection, Blog

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sahuvikramp** [comment]
Collection is ready and working on blog post.

Collection link : https://www.postman.com/postman/workspace/postman-answers/collection/18070393-2e898e89-68d8-4835-9261-5c39601ad66e?action=share&creator=18070393

**Comment by sahuvikramp** [comment]
Blog post done shared with Linda

**Comment by arlemi** [comment]
@sahuvikramp For the collection, can you add some documentation at the collection level? what is that collection for, how to use it etc. e.g. https://www.postman.com/postman/workspace/postman-answers/collection/13455110-49f59d0d-b226-4a25-9182-0054412d15d1?ctx=documentation

You can also backlink to the blog once it's posted! 

Another quick thing, and that's just me being picky, can you get all your request to start with an uppercase letter? There's a mix of uppercase and lowercase at the moment. 🙈
