### ISSUE TITLE
CFP: comparing advantages/disadvantages of REST vs gRPC APIs

### ISSUE THREAD

**Issue by iandouglas** [postmanlabs/devrel-content#81]
### Describe the content you'd like to see

I submitted a talk proposal for a REST vs gRPC comparison, and would like to flush out more of the details to refine this into a "review of REST, intro to protobuf and gRPC, then compare the two and why you would choose one over the other" kind of event talk.

### Content Type

Talk

**Comment by arlemi** [comment]
@iandouglas Would that be the "We've RESTed long enough talk"? Or is that something else you still want to create?
