### ISSUE TITLE
Video/evangelist activities for the Postman uptime monitor

### ISSUE THREAD

**Issue by charlie-postman** [postmanlabs/devrel-content#91]
### Describe the content you'd like to see

Postman monitoring team here -- We hope that our DevRel team can help with some activities/materials for our uptime monitoring product — product intro videos, online sessions, etc. We appreciate your support!

**Comment by loopDelicious** [comment]
Type: Level Up video
Title: Uptime monitoring
Description:
```
Uptime monitors continuously check the availability of a single API endpoint, website, or other URL and let you know whenever downtime occurs.
Docs: https://learning.postman.com/docs/monitoring-your-api/uptime-monitors/
Blog: https://blog.postman.com/introducing-uptime-monitor/
```
Link to video (called uptime): https://drive.google.com/drive/u/0/folders/10KLX7KOSw4n0NaXDO4aFJwXrQw-Dwpzj

Special instructions for Tobi: At 0:46, I fill in the Monitor Name field, and the Chrome auto-fill flashes some personal information. If you can trim that out, that would be preferred. But not necessary.
