### ISSUE TITLE
Persist variables in monitor

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/devrel-content#95]
### Describe the content you'd like to see

Part 2 of HackerNews alert to persist data store

### Content Type

Collection, Blog, Tutorial

IMAGE inspo: sustaining variable values (`x` and `y`) throughout a monitor run, monitoring

**Comment by loopDelicious** [comment]
in review

**Comment by arlemi** [comment]
When this will be released, there was a question about just that on this video: https://www.youtube.com/watch?v=tDQzY1Hn2LY&lc=UgxdBGJx4kTNs-KokER4AaABAg
