### ISSUE TITLE
Update the public Nanoleaf Workspace

### ISSUE THREAD

**Issue by iandouglas** [postmanlabs/devrel-content#98]
### Describe the content you'd like to see

The Nanoleaf workspace gets a LOT of top-page results on Google, but is out of date and could use a refresh.

I'll reach out to Nanoleaf to see if they have a DevRel team to make an "official" workspace as well, but in the meantime there are some updates that could be helpful to the collection.

### Content Type

Collection

**Comment by arlemi** [comment]
@iandouglas Is this regarding this collection? https://www.postman.com/postman/workspace/published-postman-templates/collection/1559645-9b06dd46-62bc-45f4-b57e-66c688823cab?ctx=documentation

Also feel free to mention Nanoleaf to the API Network evangelists, they might have already reached out to them and if not that'd be a good one to add to their list!

**Comment by iandouglas** [comment]
Yeah, if you do a Google search for "nanoleaf API", the number one hit goes to https://documenter.getpostman.com/view/1559645/RW1gEcCH which, I believe, is the generated documentation for that collection, but it needs to be updated.

**Comment by arlemi** [comment]
We've forwarded them to the API Network Evangelists so they can get their own workspace and API documentation.
